name: SocialBridge-telegram-paper
version: '0.2.0'
main: io.github.kosyakmakc.socialBridgeTelegram.paper.SocialBridgeTelegramPlugin
api-version: '1.21'
authors: [ kosyakmakc ]
depend: [SocialBridge-paper, tgbridge]
folia-supported: true